using System;

namespace AspNetConventions.Http.Models
{
    /// <summary>
    /// Provides navigation links for paginated API responses.
    /// </summary>
    /// <remarks>
    /// This class contains URIs for navigating through paginated results, enabling clients
    /// to easily move between pages without having to construct URLs manually. The links
    /// are typically generated by the <see cref="PaginationMetadata.BuildLinks"/> method
    /// and included in API responses when pagination is enabled.
    /// </remarks>
    public sealed class PaginationLinks
    {
        /// <summary>
        /// Gets or sets the URI for the first page of results.
        /// </summary>
        /// <value>The URI pointing to the first page, or null if not available.</value>
        /// <remarks>This link is always available when pagination is enabled and there are results.</remarks>
        public Uri? FirstPageUrl { get; set; }

        /// <summary>
        /// Gets or sets the URI for the last page of results.
        /// </summary>
        /// <value>The URI pointing to the last page, or null if not available.</value>
        /// <remarks>This link is always available when pagination is enabled and there are results.</remarks>
        public Uri? LastPageUrl { get; set; }

        /// <summary>
        /// Gets or sets the URI for the next page of results.
        /// </summary>
        /// <value>The URI pointing to the next page, or null if the current page is the last page.</value>
        /// <remarks>This link is null when the current page is the last page in the result set.</remarks>
        public Uri? NextPageUrl { get; set; }

        /// <summary>
        /// Gets or sets the URI for the previous page of results.
        /// </summary>
        /// <value>The URI pointing to the previous page, or null if the current page is the first page.</value>
        /// <remarks>This link is null when the current page is the first page in the result set.</remarks>
        public Uri? PreviousPageUrl { get; set; }
    }
}
