using Microsoft.Extensions.Logging;

namespace AspNetConventions.Extensions
{
    /// <summary>
    /// Provides compiled logging extensions for efficient structured logging.
    /// </summary>
    /// <remarks>
    /// This class uses the .NET source generator for high-performance structured logging.
    /// The logging methods are compiled at build time, eliminating runtime string allocation
    /// and providing better performance compared to traditional string interpolation logging.
    /// </remarks>
    internal static partial class LoggerDelegateExtensions
    {
        /// <summary>
        /// Logs an error message when processing an item encounters an exception.
        /// </summary>
        /// <param name="logger">The logger instance to write to.</param>
        /// <param name="itemId">The identifier of the item being processed.</param>
        /// <param name="itemType">The type or category of the item being processed.</param>
        /// <remarks>
        /// This method is generated by the <see cref="LoggerMessageAttribute"/> source generator and provides
        /// high-performance structured logging.
        /// </remarks>
        [LoggerMessage(
            EventId = 1,
            Level = LogLevel.Error,
            Message = "Processing item {ItemId} of type {ItemType}")]
        internal static partial void LogException(
            this ILogger logger, int itemId, string itemType);
    }
}
